
version: 2
jobs:
  build:
    docker:

      - image: circleci/node:8.11.2

    working_directory: ~/reservation

    steps:
      - checkout
      - run: npm install
      - run: npm build
      - run: npm test


